@echo off
echo Cleaning...
if exist "ipch"  rd /s /q "ipch"  && echo Removing "ipch"...
if exist "Win32" rd /s /q "Win32" && echo Removing "Win32"...
if exist "x64"   rd /s /q "x64"   && echo Removing "x64"...
for /r %%i in (*.aps) do del /q "%%i" && echo Removing "%%i"...
for /r %%i in (*.ncb) do del /q "%%i" && echo Removing "%%i"...
for /r %%i in (*.sdf) do del /q "%%i" && echo Removing "%%i"...
for /d /r %%i in (*.*) do if exist "%%i\Win32" rd /s /q "%%i\Win32" && echo Removing "%%i\Win32"...
for /d /r %%i in (*.*) do if exist "%%i\x64"   rd /s /q "%%i\x64"   && echo Cleaning %%i\x64"...
echo.
exit /b 0